# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
