# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-08 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20171008_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Tasks')),
            ],
            options={
                'verbose_name': 'Прикрепленные файлы',
                'verbose_name_plural': 'Прикрепленные файлы',
            },
        ),
        migrations.RemoveField(
            model_name='fails',
            name='task',
        ),
        migrations.DeleteModel(
            name='Fails',
        ),
    ]
