# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20171008_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='data',
            field=models.CharField(max_length=20000000),
        ),
    ]
